In [3]:
from _context import vugrad
import vugrad as vg
import numpy as np
import matplotlib.pyplot as plt


In [4]:
a = vg.TensorNode(np.random.randn(2, 2))
b = vg.TensorNode(np.random.randn(2, 2))
c = a + b

In [5]:
a.value

array([[-0.93377643, -1.12970255],
       [ 1.46772344, -0.24736857]])

In [6]:
b.value

array([[-1.1471218 ,  1.29098047],
       [-1.35104762, -0.1599634 ]])

In [7]:
c.value

array([[-2.08089822,  0.16127793],
       [ 0.11667582, -0.40733196]])

In [8]:
c.source

In [9]:
c.source.inputs[0]

In [10]:
a

In [11]:
a.grad

array([[0., 0.],
       [0., 0.]])

In [12]:
c = b + a

In [13]:
c.source.inputs[0]

In [14]:
b

In [15]:
x = np.array([[1, 2], [3, 4], [5, 6]])
sumd = x.sum(axis=1, keepdims=True)

In [16]:
sumd

array([[ 3],
       [ 7],
       [11]])

In [17]:
x/sumd

array([[0.33333333, 0.66666667],
       [0.42857143, 0.57142857],
       [0.45454545, 0.54545455]])

In [18]:
sumd2 = sumd * sumd
sumd2

array([[  9],
       [ 49],
       [121]])

In [19]:
x/sumd2

array([[0.11111111, 0.22222222],
       [0.06122449, 0.08163265],
       [0.04132231, 0.04958678]])

In [22]:
def draw_plot_two_datasets(model_1, model_2, model_1_desc_label, model_2_desc_label, y_label, title):
    train_loss_array = np.array(model_1)
    val_loss_array = np.array(model_2)

    epochs = len(model_1[0]) if len(model_1) > 0 else 0
    t = np.arange(epochs)

    mu_train = train_loss_array.mean(axis=0)
    sigma_train = train_loss_array.std(axis=0)
    mu_val = val_loss_array.mean(axis=0)
    sigma_val = val_loss_array.std(axis=0)

    fig, ax = plt.subplots(1)

    ax.plot(t, mu_train, lw=2, label=model_1_desc_label, color='blue')
    ax.fill_between(t, mu_train + sigma_train, mu_train - sigma_train, facecolor='blue', alpha=0.3)

    ax.plot(t, mu_val, lw=2, label=model_2_desc_label, color='red')
    ax.fill_between(t, mu_val + sigma_val, mu_val - sigma_val, facecolor='red', alpha=0.3)

    # ax.set_title('Training & Validation Loss Mean and ± Standard Deviation Interval')
    ax.set_title(title)
    ax.legend(loc='upper right')
    ax.set_xlabel('Epochs')
    ax.set_ylabel(y_label)
    ax.grid()

    plt.show()